trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_Extension
  displayName: Build Extension
  jobs:
  - job: Build_Package_Publish_Extension
    displayName: Build Package Publish Extension
    steps:  
    - task: TfxInstaller@3
      displayName: Install Tfx
      name: tfx_install
      inputs:
        version: 'v0.9.x'

    - task: QueryAzureDevOpsExtensionVersion@3
      displayName: Set Extension Version
      name: extension_version
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'marketplace_sc'
        publisherId: 'NipunBahri'
        extensionId: 'custom-extension'
        versionAction: 'Patch'
        outputVariable: 'Extension.Version'

    - task: PackageAzureDevOpsExtension@3
      displayName: Package Extension
      name: package_extension
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)/extension'
        publisherId: 'NipunBahri'
        extensionId: 'custom-extension'
        extensionName: 'Custom Extension'
        extensionVersion: '1.0.1'
        updateTasksVersion: true
        updateTasksVersionType: 'patch'
        extensionVisibility: 'private'
        extensionPricing: 'free'
        
    - task: PublishAzureDevOpsExtension@3
      displayName: Publish Extension
      name: publish_extension
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'marketplace_sc'
        fileType: 'vsix'
        vsixFile: '*.vsix'
        publisherId: 'NipunBahri'
        extensionId: 'custom-extension'
        extensionName: 'Custom Extension'
        extensionVisibility: 'private'
        shareWith: 'bahrinipun'

