trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- name: tfx_version
  value: v0.9.x
- name: service_connection
  value: marketplace_sc
- name: publisher_id
  value: NipunBahri
- name: extension_id
  value: custom-extension
- name: extension_name
  value: Custom Extension
- name: extension_version
  value: 1.0.2

stages:
- stage: Build_Extension
  displayName: Build Extension
  jobs:
  - job: Build_Package_Publish_Extension
    displayName: Build Package Publish Extension
    steps:  
    - task: TfxInstaller@3
      displayName: Install Tfx
      name: tfx_install
      inputs:
        version: '$(tfx_version)'

    - task: QueryAzureDevOpsExtensionVersion@3
      displayName: Set Extension Version
      name: extension_version
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: '$(service_connection)'
        publisherId: '$(publisher_id)'
        extensionId: '$(extension_id)'
        versionAction: 'Patch'
        outputVariable: 'Extension.Version'

    - task: PackageAzureDevOpsExtension@3
      displayName: Package Extension
      name: package_extension
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)/extension'
        publisherId: '$(publisher_id)'
        extensionId: '$(extension_id)'
        extensionName: '$(extension_name)'
        extensionVersion: '$(extension_version)'
        updateTasksVersion: true
        updateTasksVersionType: 'patch'
        extensionVisibility: 'private'
        extensionPricing: 'free'
        
    - task: PublishAzureDevOpsExtension@3
      displayName: Publish Extension
      name: publish_extension
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: '$(service_connection)'
        fileType: 'vsix'
        vsixFile: '*.vsix'
        publisherId: '$(publisher_id)'
        extensionId: '$(extension_id)'
        extensionName: '$(extension_name)'
        extensionVisibility: 'private'
        shareWith: 'bahrinipun'

